### ISSUE TITLE
Remember "Block" setting?

### ISSUE THREAD

**Issue by TPS** [Divested-Mobile/Carrion#1]
@SkewedZeppelin 1st of all, thank you for your work on this entire ecosystem.  It's amazing.

I don't find that Carrion remembers the "Block" setting in v1.16 from before it becomes unloaded (e.g., phone reboot) to afterwards.  Would you look at that when you have a chance?

**Comment by SkewedZeppelin** [comment]
Thanks!  A fixed build will be up in a few minutes.

**Comment by TPS** [comment]
Thanks very much! 🙇🏾‍♂️
