### ISSUE TITLE
Cannot download database

### ISSUE THREAD

**Issue by davewhb** [Divested-Mobile/Carrion#7]
Issue: 
When attempting to download a data base i get a warning that says:
"No internet, can't download database"

No other app on my phone has issues using the internet. 

Issue is present on wifi and Mobile data.

Phone is OnePlus7T using LineageOS 21. 

My phone has no google services installed. Is this required?

**Comment by SkewedZeppelin** [comment]
please verify no network restrictions are set on the app via the Settings > App info > Mobile data & Wi-fi menu

also is it possible you disable captive portal / internet connectivity checks?

**Comment by davewhb** [comment]
> please verify no network restrictions are set on the app via the Settings > App info > Mobile data & Wi-fi menu
> 
> also is it possible you disable captive portal / internet connectivity checks?

Yep, i had to enable network access. Ive Never had to do that before.  I also tested this app on another phone and didnt have the issue. Thank you for your assistance.

**Comment by SkewedZeppelin** [comment]
@davewhb 
no worries, Lineage does that sometimes, not sure why.
